### ISSUE TITLE
Warning: The 'no-unused-variable' rule requires type information.

### ISSUE THREAD

**Issue by Aajax0** [bunch-of-friends/tslint-config-bunch-of-friends#2]
With the `no-unused-variable` tslint always shows this warning ^^

**Comment by theRealRobG** [comment]
This isn't an issue with this repo. [`no-unused-variable`](https://palantir.github.io/tslint/rules/no-unused-variable/) [requires type info](https://palantir.github.io/tslint/usage/type-checking/):
> Some TSLint rules go further than linting code syntax. Semantic rules use the compiler’s program APIs to inspect static types and validate code patterns.

Wherever it is used, you need to pass a flag to the lint command, telling it where the `tsconfig.json` file is. I suggest usage should be as such:
  - From root, the `npm run lint` command should call `lerna run lint`
  - The command as is demonstrated [here](https://github.com/bunch-of-friends/lerna-typescript-jest-boilerplate/blob/master/package.json#L28) should be moved to each package and add `-p .` to the end. i.e.
```
"lint": "tslint --fix '**/*.ts{,x}' -e '**/**/*d.ts' -e '**/node_modules/**' -p ."
```

**Comment by Aajax0** [comment]
Oh I see. That makes sense. Let's change it in mse and the boilerplate
